name: Update README with latest Medium Blogs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.email "stiflerxd.ai@cudabit.live"
          git config --global user.name "STiFLeR"

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.app/feeds/dH3wfYHRhT9fP1Gj.xml"
