name: Update README with latest Medium Blogs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@stiflerxd"
