name: Update README with Medium Posts

on:
  schedule:
    - cron: '0 * * * *'  # Updates every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update recent Medium articles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@stiflerxd"
